(() => {
  if (document.getElementById('ask-keith')) return;
  const style = document.createElement('style');
  style.textContent = `#ask-keith{position:fixed;right:20px;bottom:20px;z-index:1000;font:15px/1.5 'DM Sans',sans-serif;color:#111720}#ask-keith summary{list-style:none;cursor:pointer;background:#ff6336;color:#111720;border:2px solid #111720;border-radius:30px;padding:12px 22px;font-weight:700;box-shadow:0 4px 20px #0003;min-height:48px;width:max-content;margin-left:auto}#ask-keith summary::-webkit-details-marker{display:none}#ask-keith summary:focus-visible,#ask-keith a:focus-visible,#ask-keith button:focus-visible{outline:3px solid #2371c8;outline-offset:4px}#ask-keith .ask-panel{position:absolute;right:0;bottom:66px;background:#fff;border:1px solid #dce0e5;border-radius:16px;padding:24px;width:340px;max-width:calc(100vw - 32px);max-height:calc(100dvh - 110px);overflow:auto;box-shadow:0 12px 40px #0003}#ask-keith h2{font:700 24px/1.2 'DM Sans',sans-serif;margin:0 35px 12px 0}#ask-keith p{margin:0 0 16px;font-size:15px}#ask-keith .ask-close{position:absolute;right:12px;top:12px;border:0;background:#edf0f3;border-radius:50%;width:36px;height:36px;font-size:24px;cursor:pointer;color:#111720}#ask-keith .ask-link{display:block;text-decoration:none;font-weight:700;border-radius:8px;padding:13px;margin:10px 0;text-align:center;background:#ff6336;color:#111720}#ask-keith .ask-book{background:#111720;color:#fff}#ask-keith .ask-hours{font-size:13px;color:#59616b;margin-top:16px;margin-bottom:0}body{padding-bottom:86px}@media(max-width:600px){#ask-keith{right:16px;bottom:calc(16px + env(safe-area-inset-bottom))}}`;
  document.head.append(style);
  const box = document.createElement('details'); box.id = 'ask-keith';
  const message = encodeURIComponent('Hi Keith! I found Apollo Consulting and would like to discuss a business project.\nVehicle/year:\nECU or tuning platform:\nModifications and fuel:\nGoals or questions:');
  box.innerHTML = `<summary>Ask Keith</summary><section class="ask-panel" aria-label="Contact Keith"><button class="ask-close" type="button" aria-label="Close Ask Keith">×</button><h2>Let’s discuss your business project.</h2><p>Share your shop name, project scope and technical needs with Keith.</p><a class="ask-link" href="https://wa.me/14699337075?text=${message}" target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a><a class="ask-link ask-book" href="https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ1uwmWzZYBTlf0F6ZN7jSnhNaSlM-oJDkHatsmJCgnErI9C6S3hx7M77WzOxICKiBd8jdaE5WOm" target="_blank" rel="noopener noreferrer">Book a one-hour appointment ↗</a><p class="ask-hours">Monday–Friday · 8 a.m.–6 p.m. Pacific<br>Messages open in WhatsApp. Keith replies when available.</p></section>`;
  const close = () => { box.open=false; box.querySelector('summary').focus(); };
  box.querySelector('button').addEventListener('click',close);
  box.addEventListener('keydown',event => {if(event.key==='Escape'){event.preventDefault();close();}});
  document.body.append(box);
})();
